apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-local-pv1
spec:
#  capacity:
#    storage: 10Gi
  accessModes:
  - ReadWriteMany
  # ReadWriteOnce, ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/volumes/pv1
  claimRef:
    name: test-local-pvc1
    namespace:default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - K8s-worker-node1