apiVersion: batch/v1
kind: Job
metadata:
  name: ex-job
spec:
  ttlSecondsAfterFinished: 1000
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.18.2
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never